// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"deni-be-crm/internal/handlers"
	"deni-be-crm/internal/repositories"
	"deni-be-crm/internal/services"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitHandlers(db *gorm.DB) *Handlers {
	iLeadsRepository := repositories.NewLeadsRepository(db)
	iDealsRepository := repositories.NewDealsRepository(db)
	iProductsRepository := repositories.NewProductsRepository(db)
	iProductsService := services.NewProductsService(iProductsRepository)
	iDealsService := services.NewDealsService(iDealsRepository, iProductsService)
	iLeadsService := services.NewLeadsService(iLeadsRepository, iDealsService, iProductsService)
	leadHandler := handlers.NewLeadHandler(iLeadsService)
	iUserRepository := repositories.NewUserRepository(db)
	iAuthService := services.NewAuthService(iUserRepository)
	authHandler := handlers.NewAuthHandler(iAuthService)
	iOrdersRepository := repositories.NewOrdersRepository(db)
	iCustomersRepository := repositories.NewCustomersRepository(db)
	iCustomersService := services.NewCustomersService(iCustomersRepository)
	iOrdersService := services.NewOrdersService(iOrdersRepository, iCustomersService, iDealsService)
	orderHandler := handlers.NewOrderHandler(iOrdersService, iCustomersService)
	productHandler := handlers.NewProductHandler(iProductsService)
	customerHandler := handlers.NewCustomerHandler(iCustomersService)
	dealHandler := handlers.NewDealHandler(iDealsService)
	iSubscriptionsRepository := repositories.NewSubscriptionsRepository(db)
	iSubscriptionsService := services.NewSubscriptionsService(iSubscriptionsRepository)
	subscriptionHandler := handlers.NewSubscriptionHandler(iSubscriptionsService)
	diHandlers := &Handlers{
		LeadHandler:         leadHandler,
		AuthHandler:         authHandler,
		OrderHandler:        orderHandler,
		ProductHandler:      productHandler,
		CustomerHandler:     customerHandler,
		DealHandler:         dealHandler,
		SubscriptionHandler: subscriptionHandler,
	}
	return diHandlers
}

// wire.go:

var ProviderSet = wire.NewSet(repositories.NewLeadsRepository, services.NewLeadsService, handlers.NewLeadHandler, repositories.NewUserRepository, services.NewAuthService, handlers.NewAuthHandler, repositories.NewOrdersRepository, services.NewOrdersService, handlers.NewOrderHandler, repositories.NewProductsRepository, services.NewProductsService, handlers.NewProductHandler, repositories.NewSubscriptionsRepository, services.NewSubscriptionsService, handlers.NewSubscriptionHandler, repositories.NewCustomersRepository, services.NewCustomersService, handlers.NewCustomerHandler, repositories.NewDealsRepository, services.NewDealsService, handlers.NewDealHandler)
